global:
  smtp_smarthost: maildev:25
  smtp_from: noreply-alert@sl.com
  smtp_hello: alertmanager
  smtp_require_tls: false

route:
  group_by:
    - alertname
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 10m
  receiver: email

receivers:
  - name: "email"
    email_configs:
      - to: mon@sl.com
        send_resolved: true
