global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8080
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://web1
          - http://web2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

rule_files:
  - prometheus.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
